// <auto-generated />
using System;
using ApiRRHH.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRRHH.Services.Migrations
{
    [DbContext(typeof(ApiRRHHContext))]
    [Migration("20221206122958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRRHH.Services.Models.Candidato", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("Candidatos");

                    b.HasData(
                        new
                        {
                            Dni = 28574087,
                            Apellido = "HIDALGO",
                            Email = "sebahidalgo@hotmail.com",
                            FechaNacimiento = new DateTime(1981, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "SEBASTIAN",
                            Telefono = "3492669439"
                        },
                        new
                        {
                            Dni = 31333444,
                            Apellido = "PEREZ",
                            Email = "lperez@hotmail.com",
                            FechaNacimiento = new DateTime(1985, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "LORENZO",
                            Telefono = "34926694444"
                        },
                        new
                        {
                            Dni = 18222444,
                            Apellido = "GOMEZ",
                            Email = "lperez@hotmail.com",
                            FechaNacimiento = new DateTime(1985, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "JUAN",
                            Telefono = "34926694444"
                        },
                        new
                        {
                            Dni = 15111444,
                            Apellido = "PEREZ",
                            Email = "lperez@hotmail.com",
                            FechaNacimiento = new DateTime(1985, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "NICOLAS",
                            Telefono = "34926694444"
                        });
                });

            modelBuilder.Entity("ApiRRHH.Services.Models.Empleo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Empleos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidatoId = 28574087,
                            NombreEmpresa = "Megatone.Net",
                            Periodo = "2021-02 2021-06"
                        },
                        new
                        {
                            Id = 2,
                            CandidatoId = 28574087,
                            NombreEmpresa = "Megatone.Net",
                            Periodo = "2021-07 2021-12"
                        },
                        new
                        {
                            Id = 3,
                            CandidatoId = 28574087,
                            NombreEmpresa = "Megatone.Net",
                            Periodo = "2022-01 2022-06"
                        },
                        new
                        {
                            Id = 4,
                            CandidatoId = 15111444,
                            NombreEmpresa = "MegaCash",
                            Periodo = "2021-02 2021-06"
                        },
                        new
                        {
                            Id = 5,
                            CandidatoId = 15111444,
                            NombreEmpresa = "Megatone.Net",
                            Periodo = "2021-07 2021-12"
                        },
                        new
                        {
                            Id = 6,
                            CandidatoId = 18222444,
                            NombreEmpresa = "Megatone.Net",
                            Periodo = "2022-01 2022-06"
                        });
                });

            modelBuilder.Entity("ApiRRHH.Services.Models.Empleo", b =>
                {
                    b.HasOne("ApiRRHH.Services.Models.Candidato", "Candidato")
                        .WithMany("Empleos")
                        .HasForeignKey("CandidatoId")
                        .IsRequired()
                        .HasConstraintName("FK_Empleos_Candidatos");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("ApiRRHH.Services.Models.Candidato", b =>
                {
                    b.Navigation("Empleos");
                });
#pragma warning restore 612, 618
        }
    }
}
